#vim character override issue, caught by default ~/.bashrc, delete it and touch new ~/.bashrc will be fine
# alias ec='emacsclient -t'
alias ec='emacs -nw'
alias halt='halt -p'
# alias scp='scp -P 0 -i /home/jusss/.ssh/id_rsa'
# alias ssh='ssh -p 0 x@jusss.org'
alias poweroff='systemctl poweroff'
alias suspend='systemctl suspend'
alias standby='sleep 1&&xset dpms force standby'
alias cr='chromium'
alias ls='ls --color'
